# Generated by Django 3.2.8 on 2022-01-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientClasses',
            fields=[
                ('ic_id', models.AutoField(primary_key=True, serialize=False)),
                ('iclassname', models.CharField(default='default', max_length=20, verbose_name='Ingredient Class Name')),
            ],
            options={
                'db_table': 'ingredientclasses',
            },
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('iname', models.CharField(default='default', max_length=30, verbose_name='Ingredient Name')),
                ('icost', models.FloatField(blank=True, default=0.0, verbose_name='Cost')),
                ('iclassid', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='iClassID', to='database.ingredientclasses', verbose_name='Ingredient-Class ID')),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='recipeClasses',
            fields=[
                ('rc_id', models.AutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(default='default', max_length=20, verbose_name='Recipe Class Name')),
            ],
            options={
                'db_table': 'recipeclasses',
            },
        ),
        migrations.CreateModel(
            name='times',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.FloatField(default=0.0)),
                ('attribute', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'times',
            },
        ),
        migrations.CreateModel(
            name='tools',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('toolname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tools',
            },
        ),
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipename', models.CharField(max_length=30)),
                ('instructions', models.CharField(max_length=3000)),
                ('image', models.ImageField(blank=True, upload_to='photos')),
                ('cooktimeid', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cookTimeID', to='database.times', verbose_name='Cook Time ID')),
                ('rclassid', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='rClassID', to='database.recipeclasses', verbose_name='Recipe-Class ID')),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='recipe_tools',
            fields=[
                ('rt_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipeid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.DO_NOTHING, to='database.recipes', verbose_name='Recipe Name')),
                ('toolid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.DO_NOTHING, to='database.tools', verbose_name='Tool Name')),
            ],
            options={
                'db_table': 'recipe_tools',
            },
        ),
        migrations.CreateModel(
            name='recipe_ingredients',
            fields=[
                ('ri_id', models.AutoField(primary_key=True, serialize=False)),
                ('measurement', models.CharField(blank=True, max_length=20)),
                ('iid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.DO_NOTHING, to='database.ingredients', verbose_name='Ingredient')),
                ('recipeid', models.ForeignKey(default='default', on_delete=django.db.models.deletion.DO_NOTHING, to='database.recipes', verbose_name='Recipe')),
            ],
            options={
                'db_table': 'recipe_ingredients',
            },
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipeid', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipeID', to='database.recipes', verbose_name='Recipe ID')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='grocery',
            fields=[
                ('grocery_id', models.AutoField(primary_key=True, serialize=False)),
                ('iid', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='iID', to='database.ingredients', verbose_name='Ingredient ID')),
            ],
            options={
                'db_table': 'grocery',
            },
        ),
    ]
