# Generated by Django 3.2.8 on 2022-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20220122_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='quantity',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
