# Generated by Django 3.2.8 on 2022-02-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_shopping_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, default='photos/none.png', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='itemname',
            field=models.CharField(default='default', max_length=100, verbose_name='Item Name'),
        ),
    ]
